/* TIGER SDK OVERLAY: generated by make-cg-hooks.sh, do not edit.

   The SDK's own CGAffineTransform.h, then the declarations Mac OS X 10.4 is missing.
   The guard appends CGCompat.h only at the outermost CoreGraphics include, so
   that it runs once every CoreGraphics type has been declared.
   See compat/CG-SURVEY.md for what CGCompat.h adds and why. */
#ifdef TIGER_CG_HOOK_ACTIVE
#include "/Users/shg/Developer/WebKitTiger/sdk/MacOSX10.4u.sdk/System/Library/Frameworks/ApplicationServices.framework/Frameworks/CoreGraphics.framework/Headers/CGAffineTransform.h"
#else
#define TIGER_CG_HOOK_ACTIVE 1
#include "/Users/shg/Developer/WebKitTiger/sdk/MacOSX10.4u.sdk/System/Library/Frameworks/ApplicationServices.framework/Frameworks/CoreGraphics.framework/Headers/CGAffineTransform.h"
#include <TigerCompat/CGCompat.h>
#undef TIGER_CG_HOOK_ACTIVE
#endif
