#!/bin/sh
# TIGER SDK OVERLAY: (re)generate the CoreGraphics headers that pull in
# <TigerCompat/CGCompat.h>.
#
# WebCore includes <CoreGraphics/CoreGraphics.h> and eleven sub-headers by name,
# and expects every modern CG function, constant and enum to be declared. The
# 10.4u SDK declares none of them. Each header listed here is replaced by a
# three-line file that includes the SDK's real header and then CGCompat.h.
#
# Why an absolute include and not #include_next: the SDK's CoreGraphics is a
# SUBFRAMEWORK of ApplicationServices, so there is no second framework
# directory named CoreGraphics for #include_next to find. It fails with
# "file not found". The absolute path is the same thing the overlay's symlinks
# already hardcode, and re-running this script fixes both after a move.
#
# The TIGER_CG_HOOK_ACTIVE guard is what makes this work. CoreGraphics headers
# include each other, so without it a translation unit that includes a leaf like
# CGGeometry.h would reach CGCompat.h before the rest of CoreGraphics had been
# emitted -- and CGCompat.h's own include of CoreGraphics.h would then be a
# no-op, because the umbrella's include guard is already set. CGColorSpaceRef
# would be undeclared. The guard makes only the OUTERMOST hook append
# CGCompat.h; every nested one just includes the SDK header.
#
# make-overlay.sh leaves real files alone, so these survive an overlay rebuild.
set -e
WKT=${WKT:-/Users/shg/Developer/WebKitTiger}
SDK=$WKT/sdk/MacOSX10.4u.sdk/System/Library/Frameworks/ApplicationServices.framework/Frameworks/CoreGraphics.framework/Headers
HERE=$(cd "$(dirname "$0")" && pwd)

# CoreGraphics.h covers 52 of the 60 include sites; the rest name a sub-header
# directly, in a translation unit that need not include the umbrella.
# CGBase.h is deliberately absent: it belongs to the CGFloat overlay, and
# hooking it would drag all of CoreGraphics into every CG include.
HEADERS="CoreGraphics.h CGContext.h CGGeometry.h CGPath.h CGImage.h CGColor.h
         CGBitmapContext.h CGColorSpace.h CGFont.h CGDataProvider.h
         CGAffineTransform.h CGPDFDocument.h"

for base in $HEADERS; do
    if [ ! -f "$SDK/$base" ]; then
        echo "no such SDK header: $SDK/$base" >&2
        exit 1
    fi
    rm -f "$HERE/$base"
    cat > "$HERE/$base" <<EOF
/* TIGER SDK OVERLAY: generated by make-cg-hooks.sh, do not edit.

   The SDK's own $base, then the declarations Mac OS X 10.4 is missing.
   The guard appends CGCompat.h only at the outermost CoreGraphics include, so
   that it runs once every CoreGraphics type has been declared.
   See compat/CG-SURVEY.md for what CGCompat.h adds and why. */
#ifdef TIGER_CG_HOOK_ACTIVE
#include "$SDK/$base"
#else
#define TIGER_CG_HOOK_ACTIVE 1
#include "$SDK/$base"
#include <TigerCompat/CGCompat.h>
#undef TIGER_CG_HOOK_ACTIVE
#endif
EOF
done

echo "CoreGraphics hooks regenerated: $HERE"
