// GENERATED by spike/gpureplay/make-tombstones.sh -- do not edit.
// The Objective-C half of the tombstones: .objc_class_name_X in the fragile
// runtime is a class structure, not an address, so these are empty classes.
// ponytail: same upgrade path as tombstones.s.

#import <Foundation/Foundation.h>

@interface JSContext : NSObject @end
@implementation JSContext @end

@interface JSValue : NSObject @end
@implementation JSValue @end

@interface NSScrollerImp : NSObject @end
@implementation NSScrollerImp @end

@interface WebArchiveResourceFromNSAttributedString : NSObject @end
@implementation WebArchiveResourceFromNSAttributedString @end

@interface _NSScrollingMomentumCalculator : NSObject @end
@implementation _NSScrollingMomentumCalculator @end
