#!/usr/bin/env python3
# Regenerates WebKit/Source/WebCore/platform/tiger64/PublicSuffixData.h from the public suffix list:
#   curl -sfLO https://publicsuffix.org/list/public_suffix_list.dat
#   tools/gen-public-suffix.py public_suffix_list.dat > WebKit/Source/WebCore/platform/tiger64/PublicSuffixData.h
import sys

rules, wildcards, exceptions = set(), set(), set()
version = ""
for line in open(sys.argv[1], encoding="utf-8"):
    line = line.strip()
    if line.startswith("// VERSION:"):
        version = line[3:]
    if not line or line.startswith("//"):
        continue
    rule = line.split()[0]
    try:  # hosts reach WebCore in punycode
        rule = ".".join(l if l == "*" or l.startswith("!") else l.encode("idna").decode() for l in rule.split("."))
    except UnicodeError:
        continue
    if rule.startswith("!"):
        exceptions.add(rule[1:])
    elif rule.startswith("*."):
        wildcards.add(rule[2:])
    else:
        rules.add(rule)

def table(name, items):
    out = ["static const char* const %s[] = {" % name]
    out += ['    "%s",' % s for s in sorted(items)]  # sorted bytewise: PublicSuffixStoreTiger64 binary-searches with strcmp
    out.append("};")
    return "\n".join(out)

print("// Generated by WebKitTiger tools/gen-public-suffix.py from publicsuffix.org, %s. Do not edit." % version)
print("#pragma once\n")
print(table("publicSuffixRules", rules))
print(table("publicSuffixWildcards", wildcards))
print(table("publicSuffixExceptions", exceptions))
