#!/usr/bin/env python3
"""Emit link tombstones for symbols an i386 Tiger executable references but never calls.

usage: make-tombstones.py MANGLED_LIST OUT.c OUT.mm [EXCLUDE_REGEX]

Each C/C++ symbol becomes a stub under its mangled name that reports the name and
exits, so a call that does reach one is named instead of wandering (or trapping
into the box's crash reporter). Each
.objc_class_name_X becomes an empty class, since in the fragile runtime that
symbol is the class structure itself. Get MANGLED_LIST from the link's
"Undefined symbols" report mapped through nm -u / c++filt (see NOTES.md).
"""
import re, sys
src, out_c, out_mm = sys.argv[1:4]
exclude = re.compile(sys.argv[4]) if len(sys.argv) > 4 else None
syms = [s.strip() for s in open(src) if s.strip()]
if exclude:
    syms = [s for s in syms if not exclude.search(s)]
objc = sorted(s[len(".objc_class_name_"):] for s in syms if s.startswith(".objc_class_name_"))
plain = sorted(s for s in syms if not s.startswith(".objc_class_name_"))
hdr = "// GENERATED by tools/make-tombstones.py -- do not edit; regenerate from the link report.\n"
with open(out_c, "w") as f:
    f.write(hdr + "// ponytail: each name here is either a file to bring back with a Tiger arm or a\n"
            "// symbol this process never calls. Reaching one names itself and exits.\n\n")
    f.write("// Reaching one reports its name on stderr and exits: a trap would hand the process\n"
            "// to 10.4's crashdump, which chokes on these binaries and has wedged the box.\n"
            "extern void tiger_tombstone_hit(const char*) __attribute__((noreturn));\n\n")
    for i, s in enumerate(plain):
        # asm labels take the symbol as the assembler sees it, leading underscore included.
        f.write(f'__attribute__((used, noreturn)) void tombstone_{i}(void) __asm__("{s}");\n'
                f'void tombstone_{i}(void) {{ tiger_tombstone_hit("{s}"); }}\n')
with open(out_mm, "w") as f:
    f.write(hdr + "#import <Foundation/Foundation.h>\n\n")
    for c in objc:
        f.write(f"@interface {c} : NSObject @end\n@implementation {c} @end\n\n")
print(f"{len(plain)} tombstones, {len(objc)} classes")
