#!/usr/bin/env python3
"""Emit link tombstones for symbols an i386 Tiger executable references but never calls.

usage: make-tombstones.py MANGLED_LIST OUT.c OUT.mm [EXCLUDE_REGEX]

Each C/C++ symbol becomes 256 bytes of 0xCC (int3) under its mangled name, so a
call that does reach one traps at the tombstone instead of wandering. Each
.objc_class_name_X becomes an empty class, since in the fragile runtime that
symbol is the class structure itself. Get MANGLED_LIST from the link's
"Undefined symbols" report mapped through nm -u / c++filt (see NOTES.md).
"""
import re, sys
src, out_c, out_mm = sys.argv[1:4]
exclude = re.compile(sys.argv[4]) if len(sys.argv) > 4 else None
syms = [s.strip() for s in open(src) if s.strip()]
if exclude:
    syms = [s for s in syms if not exclude.search(s)]
objc = sorted(s[len(".objc_class_name_"):] for s in syms if s.startswith(".objc_class_name_"))
plain = sorted(s for s in syms if not s.startswith(".objc_class_name_"))
hdr = "// GENERATED by tools/make-tombstones.py -- do not edit; regenerate from the link report.\n"
with open(out_c, "w") as f:
    f.write(hdr + "// ponytail: each name here is either a file to bring back with a Tiger arm or a\n"
            "// symbol this process never calls. 0xCC so reaching one traps.\n\n")
    for i, s in enumerate(plain):
        # asm labels take the symbol as the assembler sees it, leading underscore included.
        f.write(f'__attribute__((used)) char tombstone_{i}[256] __asm__("{s}") = {{[0 ... 255] = (char)0xCC}};\n')
with open(out_mm, "w") as f:
    f.write(hdr + "#import <Foundation/Foundation.h>\n\n")
    for c in objc:
        f.write(f"@interface {c} : NSObject @end\n@implementation {c} @end\n\n")
print(f"{len(plain)} tombstones, {len(objc)} classes")
